markdown: rdiscount
pygments: true

title_tag_text: Mrityunjay, My Profile
h1_tag_text: Mrityunjay Ravi Iyer

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
